// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyorrvkkeclwxjhzefyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5b3JydmtrZWNsd3hqaHplZnl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMTM0NDUsImV4cCI6MjA2MTU4OTQ0NX0.-D1rPC_KMNNqwZq6xANYvhm-MNDYPlS5B-nDX9Lkto0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);